Repository abn15/PassengerCounterApp, pull requests merged in 2022-10, with the labels that each got.

#10 license added
  index.css
  index.html
  license.txt
Labels: hacktober-accepted, hacktoberfest

#15 Added the child increment
  index.css
  index.html
  index.js
Labels: enhancement

#25 Made website fully responsive for mobile
  index.css
  index.html
Labels: enhancement, hacktober-accepted, hacktoberfest

#31 background
  images/bg.jpeg
Labels: good first issue, hacktober-accepted, hacktoberfest
